version: '3'

services:
  web:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - db_data:/data/db
    ports:
      - '27017:27017'
volumes:
  db_data:
